---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - _snippets/*
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/**/*

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile.rb

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile.rb

Naming/FileName:
  Enabled: true
  Exclude:
    - Rakefile.rb

Style/IfUnlessModifier:
  Enabled: true
  Exclude:
    - app/forms/auth.rb

Style/RedundantFreeze:
  Enabled: true
  Exclude:
    - app/forms/form_base.rb

Style/RedundantRegexpEscape:
  Enabled: true
  Exclude:
    - app/forms/form_base.rb

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - app/models/internship.rb
    - app/models/interview.rb

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/models/internship.rb
    - app/models/interview.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/*

Style/HashLikeCase:
  Enabled: true
  Exclude:
    - app/services/transform_module.rb